In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
try:
    df = pd.read_csv('/content/Online Retail Data Set.csv', encoding='ISO-8859-1')
    display(df)
except FileNotFoundError:
    print("Error: The file '/content/Online Retail Data Set.csv' was not found. Please ensure it's uploaded or the path is correct.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

,ï»¿InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ï»¿InvoiceNo  541909 non-null  object
 1   StockCode     541909 non-null  object
 2   Description   540455 non-null  object
 3   Quantity      541909 non-null  int64
 4   InvoiceDate   541909 non-null  object
 5   UnitPrice     541909 non-null  float64
 6   CustomerID    406829 non-null  float64
 7   Country       541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [12]:
print(df.isnull().sum())

ï»¿InvoiceNo         0
StockCode            0
Description       1454
Quantity             0
InvoiceDate          0
UnitPrice            0
CustomerID      135080
Country              0
dtype: int64

In [14]:
# Drop rows where any column has a null value
df_cleaned = df.dropna().copy()

print(f"Original DataFrame shape: {df.shape}")
print(f"Cleaned DataFrame shape: {df_cleaned.shape}")

Original DataFrame shape: (541909, 8)
Cleaned DataFrame shape: (406829, 8)

In [15]:
print("Info for df_cleaned:")
df_cleaned.info()

Info for df_cleaned:
<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ï»¿InvoiceNo  406829 non-null  object
 1   StockCode     406829 non-null  object
 2   Description   406829 non-null  object
 3   Quantity      406829 non-null  int64
 4   InvoiceDate   406829 non-null  object
 5   UnitPrice     406829 non-null  float64
 6   CustomerID    406829 non-null  float64
 7   Country       406829 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 27.9+ MB

In [19]:
df_cleaned['InvoiceDate'] = pd.to_datetime(df_cleaned['InvoiceDate'], errors='coerce')

# Check if any dates were coerced to NaT
nat_count = df_cleaned['InvoiceDate'].isnull().sum()
if nat_count > 0:
    print(f"Warning: {nat_count} invalid dates were converted to NaT.")
    # Optionally, you can drop these rows or fill them with a placeholder
    # df_cleaned.dropna(subset=['InvoiceDate'], inplace=True)

print("Updated info for df_cleaned after converting InvoiceDate:")
df_cleaned.info()

print("\nFirst 5 rows with updated InvoiceDate:")
display(df_cleaned)

Updated info for df_cleaned after converting InvoiceDate:
<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ï»¿InvoiceNo  406829 non-null  object
 1   StockCode     406829 non-null  object
 2   Description   406829 non-null  object
 3   Quantity      406829 non-null  int64
 4   InvoiceDate   406829 non-null  datetime64[ns]
 5   UnitPrice     406829 non-null  float64
 6   CustomerID    406829 non-null  float64
 7   Country       406829 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.9+ MB

First 5 rows with updated InvoiceDate:

,ï»¿InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [20]:
df_cleaned.to_csv('Online_Retail_Data_Cleaned.csv', index=False)
print('Cleaned DataFrame saved to Online_Retail_Data_Cleaned.csv')

Cleaned DataFrame saved to Online_Retail_Data_Cleaned.csv